#############################################################################
# Makefile for building: harbour-tidalplayer
# Generated by qmake (3.1) (Qt 5.15.13)
# Project:  harbour-tidalplayer.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile harbour-tidalplayer.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = harbour-tidalplayer1.0.0
DISTDIR = /home/runner/work/harbour-tidalplayer/harbour-tidalplayer/.tmp/harbour-tidalplayer1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       =  
OBJECTS       = 
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		harbour-tidalplayer.pro  
QMAKE_TARGET  = harbour-tidalplayer
DESTDIR       = 
TARGET        = harbour-tidalplayer


first: all
####### Build rules

harbour-tidalplayer: python/tidalapi/__init__.py python/tidalapi/album.py python/tidalapi/artist.py python/tidalapi/exceptions.py python/tidalapi/genre.py python/tidalapi/media.py python/tidalapi/mix.py python/tidalapi/page.py python/tidalapi/playlist.py python/tidalapi/request.py python/tidalapi/session.py python/tidalapi/types.py python/tidalapi/user.py python/tidalapi/workers.py python/mpegdash/__init__.py python/mpegdash/nodes.py python/mpegdash/parser.py python/mpegdash/prettyprinter.py python/mpegdash/utils.py python/ratelimit/__init__.py python/ratelimit/decorators.py python/ratelimit/exception.py python/ratelimit/utils.py python/typing_extensions/_typed_dict_test_helper.py python/typing_extensions/test_typing_extensions.py python/typing_extensions/typing_extensions.py python/dateutil/__init__.py python/dateutil/_common.py python/dateutil/easter.py python/dateutil/relativedelta.py python/dateutil/rrule.py python/dateutil/tzwin.py python/dateutil/utils.py python/dateutil/parser/__init__.py python/dateutil/parser/_parser.py python/dateutil/parser/isoparser.py python/isodate/setup.py python/isodate/src python/python-future/setup.py python/python-future/src python/six/setup.py python/six/six.py  python/pyaes/__init__.py python/pyaes/aes.py python/pyaes/blockfeeder.py python/pyaes/util.py $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: harbour-tidalplayer.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		harbour-tidalplayer.pro
	$(QMAKE) -o Makefile harbour-tidalplayer.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
harbour-tidalplayer.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile harbour-tidalplayer.pro

qmake_all: FORCE


all: Makefile harbour-tidalplayer

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents external/tidalapi/__init__.py external/tidalapi/album.py external/tidalapi/artist.py external/tidalapi/exceptions.py external/tidalapi/genre.py external/tidalapi/media.py external/tidalapi/mix.py external/tidalapi/page.py external/tidalapi/playlist.py external/tidalapi/request.py external/tidalapi/session.py external/tidalapi/types.py external/tidalapi/user.py external/tidalapi/workers.py $(DISTDIR)/
	$(COPY_FILE) --parents external/mpegdash/mpegdash/__init__.py external/mpegdash/mpegdash/nodes.py external/mpegdash/mpegdash/parser.py external/mpegdash/mpegdash/prettyprinter.py external/mpegdash/mpegdash/utils.py $(DISTDIR)/
	$(COPY_FILE) --parents external/ratelimit/ratelimit/__init__.py external/ratelimit/ratelimit/decorators.py external/ratelimit/ratelimit/exception.py external/ratelimit/ratelimit/utils.py $(DISTDIR)/
	$(COPY_FILE) --parents external/typing_extensions-4.12.2/src/_typed_dict_test_helper.py external/typing_extensions-4.12.2/src/test_typing_extensions.py external/typing_extensions-4.12.2/src/typing_extensions.py $(DISTDIR)/
	$(COPY_FILE) --parents external/dateutil-2.8.2/dateutil/__init__.py external/dateutil-2.8.2/dateutil/_common.py external/dateutil-2.8.2/dateutil/easter.py external/dateutil-2.8.2/dateutil/relativedelta.py external/dateutil-2.8.2/dateutil/rrule.py external/dateutil-2.8.2/dateutil/tzwin.py external/dateutil-2.8.2/dateutil/utils.py $(DISTDIR)/
	$(COPY_FILE) --parents external/dateutil-2.8.2/dateutil/parser/__init__.py external/dateutil-2.8.2/dateutil/parser/_parser.py external/dateutil-2.8.2/dateutil/parser/isoparser.py $(DISTDIR)/
	$(COPY_FILE) --parents external/isodate-0.6.1/setup.py $(DISTDIR)/
	$(COPY_FILE) --parents external/isodate-0.6.1/src $(DISTDIR)/
	$(COPY_FILE) --parents external/python-future-1.0.0/setup.py $(DISTDIR)/
	$(COPY_FILE) --parents external/python-future-1.0.0/src $(DISTDIR)/
	$(COPY_FILE) --parents external/six-1.12.0/setup.py $(DISTDIR)/
	$(COPY_FILE) --parents external/six-1.12.0/six.py $(DISTDIR)/
	$(COPY_FILE) --parents external/pyaes-1.6.1/setup.py $(DISTDIR)/
	$(COPY_FILE) --parents external/pyaes-1.6.1/pyaes $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_copy_tidalpython_make_all: python/tidalapi/__init__.py python/tidalapi/album.py python/tidalapi/artist.py python/tidalapi/exceptions.py python/tidalapi/genre.py python/tidalapi/media.py python/tidalapi/mix.py python/tidalapi/page.py python/tidalapi/playlist.py python/tidalapi/request.py python/tidalapi/session.py python/tidalapi/types.py python/tidalapi/user.py
python/tidalapi/__init__.py: external/tidalapi/__init__.py
	$(QINSTALL) external/tidalapi/__init__.py python/tidalapi/__init__.py

python/tidalapi/album.py: external/tidalapi/album.py
	$(QINSTALL) external/tidalapi/album.py python/tidalapi/album.py

python/tidalapi/artist.py: external/tidalapi/artist.py
	$(QINSTALL) external/tidalapi/artist.py python/tidalapi/artist.py

python/tidalapi/exceptions.py: external/tidalapi/exceptions.py
	$(QINSTALL) external/tidalapi/exceptions.py python/tidalapi/exceptions.py

python/tidalapi/genre.py: external/tidalapi/genre.py
	$(QINSTALL) external/tidalapi/genre.py python/tidalapi/genre.py

python/tidalapi/media.py: external/tidalapi/media.py
	$(QINSTALL) external/tidalapi/media.py python/tidalapi/media.py

python/tidalapi/mix.py: external/tidalapi/mix.py
	$(QINSTALL) external/tidalapi/mix.py python/tidalapi/mix.py

python/tidalapi/page.py: external/tidalapi/page.py
	$(QINSTALL) external/tidalapi/page.py python/tidalapi/page.py

python/tidalapi/playlist.py: external/tidalapi/playlist.py
	$(QINSTALL) external/tidalapi/playlist.py python/tidalapi/playlist.py

python/tidalapi/request.py: external/tidalapi/request.py
	$(QINSTALL) external/tidalapi/request.py python/tidalapi/request.py

python/tidalapi/session.py: external/tidalapi/session.py
	$(QINSTALL) external/tidalapi/session.py python/tidalapi/session.py

python/tidalapi/types.py: external/tidalapi/types.py
	$(QINSTALL) external/tidalapi/types.py python/tidalapi/types.py

python/tidalapi/user.py: external/tidalapi/user.py
	$(QINSTALL) external/tidalapi/user.py python/tidalapi/user.py

compiler_copy_mpegdash_make_all: python/mpegdash/__init__.py python/mpegdash/nodes.py python/mpegdash/parser.py python/mpegdash/prettyprinter.py python/mpegdash/utils.py
python/mpegdash/__init__.py: external/mpegdash/mpegdash/__init__.py
	$(QINSTALL) external/mpegdash/mpegdash/__init__.py python/mpegdash/__init__.py

python/mpegdash/nodes.py: external/mpegdash/mpegdash/nodes.py
	$(QINSTALL) external/mpegdash/mpegdash/nodes.py python/mpegdash/nodes.py

python/mpegdash/parser.py: external/mpegdash/mpegdash/parser.py
	$(QINSTALL) external/mpegdash/mpegdash/parser.py python/mpegdash/parser.py

python/mpegdash/prettyprinter.py: external/mpegdash/mpegdash/prettyprinter.py
	$(QINSTALL) external/mpegdash/mpegdash/prettyprinter.py python/mpegdash/prettyprinter.py

python/mpegdash/utils.py: external/mpegdash/mpegdash/utils.py
	$(QINSTALL) external/mpegdash/mpegdash/utils.py python/mpegdash/utils.py

compiler_copy_ratelimit_make_all: python/ratelimit/__init__.py python/ratelimit/decorators.py python/ratelimit/exception.py python/ratelimit/utils.py
python/ratelimit/__init__.py: external/ratelimit/ratelimit/__init__.py
	$(QINSTALL) external/ratelimit/ratelimit/__init__.py python/ratelimit/__init__.py

python/ratelimit/decorators.py: external/ratelimit/ratelimit/decorators.py
	$(QINSTALL) external/ratelimit/ratelimit/decorators.py python/ratelimit/decorators.py

python/ratelimit/exception.py: external/ratelimit/ratelimit/exception.py
	$(QINSTALL) external/ratelimit/ratelimit/exception.py python/ratelimit/exception.py

python/ratelimit/utils.py: external/ratelimit/ratelimit/utils.py
	$(QINSTALL) external/ratelimit/ratelimit/utils.py python/ratelimit/utils.py

compiler_copy_typing_make_all: python/typing_extensions/_typed_dict_test_helper.py python/typing_extensions/test_typing_extensions.py python/typing_extensions/typing_extensions.py
python/typing_extensions/_typed_dict_test_helper.py: external/typing_extensions-4.12.2/src/_typed_dict_test_helper.py
	$(QINSTALL) external/typing_extensions-4.12.2/src/_typed_dict_test_helper.py python/typing_extensions/_typed_dict_test_helper.py

python/typing_extensions/test_typing_extensions.py: external/typing_extensions-4.12.2/src/test_typing_extensions.py
	$(QINSTALL) external/typing_extensions-4.12.2/src/test_typing_extensions.py python/typing_extensions/test_typing_extensions.py

python/typing_extensions/typing_extensions.py: external/typing_extensions-4.12.2/src/typing_extensions.py
	$(QINSTALL) external/typing_extensions-4.12.2/src/typing_extensions.py python/typing_extensions/typing_extensions.py

compiler_copy_dateutil_make_all: python/dateutil/__init__.py python/dateutil/_common.py python/dateutil/easter.py python/dateutil/relativedelta.py python/dateutil/rrule.py python/dateutil/tzwin.py python/dateutil/utils.py
python/dateutil/__init__.py: external/dateutil-2.8.2/dateutil/__init__.py
	$(QINSTALL) external/dateutil-2.8.2/dateutil/__init__.py python/dateutil/__init__.py

python/dateutil/_common.py: external/dateutil-2.8.2/dateutil/_common.py
	$(QINSTALL) external/dateutil-2.8.2/dateutil/_common.py python/dateutil/_common.py

python/dateutil/easter.py: external/dateutil-2.8.2/dateutil/easter.py
	$(QINSTALL) external/dateutil-2.8.2/dateutil/easter.py python/dateutil/easter.py

python/dateutil/relativedelta.py: external/dateutil-2.8.2/dateutil/relativedelta.py
	$(QINSTALL) external/dateutil-2.8.2/dateutil/relativedelta.py python/dateutil/relativedelta.py

python/dateutil/rrule.py: external/dateutil-2.8.2/dateutil/rrule.py
	$(QINSTALL) external/dateutil-2.8.2/dateutil/rrule.py python/dateutil/rrule.py

python/dateutil/tzwin.py: external/dateutil-2.8.2/dateutil/tzwin.py
	$(QINSTALL) external/dateutil-2.8.2/dateutil/tzwin.py python/dateutil/tzwin.py

python/dateutil/utils.py: external/dateutil-2.8.2/dateutil/utils.py
	$(QINSTALL) external/dateutil-2.8.2/dateutil/utils.py python/dateutil/utils.py

compiler_copy_dateutilparser_make_all: python/dateutil/parser/__init__.py python/dateutil/parser/_parser.py python/dateutil/parser/isoparser.py
python/dateutil/parser/__init__.py: external/dateutil-2.8.2/dateutil/parser/__init__.py
	$(QINSTALL) external/dateutil-2.8.2/dateutil/parser/__init__.py python/dateutil/parser/__init__.py

python/dateutil/parser/_parser.py: external/dateutil-2.8.2/dateutil/parser/_parser.py
	$(QINSTALL) external/dateutil-2.8.2/dateutil/parser/_parser.py python/dateutil/parser/_parser.py

python/dateutil/parser/isoparser.py: external/dateutil-2.8.2/dateutil/parser/isoparser.py
	$(QINSTALL) external/dateutil-2.8.2/dateutil/parser/isoparser.py python/dateutil/parser/isoparser.py

compiler_copy_isodate_setup_make_all: python/isodate/setup.py
python/isodate/setup.py: external/isodate-0.6.1/setup.py
	$(QINSTALL) external/isodate-0.6.1/setup.py python/isodate/setup.py

compiler_copy_isodate_src_make_all: python/isodate/src
python/isodate/src: external/isodate-0.6.1/src
	$(QINSTALL) external/isodate-0.6.1/src python/isodate/src

compiler_copy_future_setup_make_all: python/python-future/setup.py
python/python-future/setup.py: external/python-future-1.0.0/setup.py
	$(QINSTALL) external/python-future-1.0.0/setup.py python/python-future/setup.py

compiler_copy_future_src_make_all: python/python-future/src
python/python-future/src: external/python-future-1.0.0/src
	$(QINSTALL) external/python-future-1.0.0/src python/python-future/src

compiler_copy_six_setup_make_all: python/six/setup.py
python/six/setup.py: external/six-1.12.0/setup.py
	$(QINSTALL) external/six-1.12.0/setup.py python/six/setup.py

compiler_copy_six_module_make_all: python/six/six.py
python/six/six.py: external/six-1.12.0/six.py
	$(QINSTALL) external/six-1.12.0/six.py python/six/six.py

compiler_copy_pyaes_setup_make_all: python/pyaes/setup.py
python/pyaes/setup.py: external/pyaes-1.6.1/setup.py
	$(QINSTALL) external/pyaes-1.6.1/setup.py python/pyaes/setup.py

compiler_copy_pyaes_make_all: python/pyaes/__init__.py python/pyaes/aes.py python/pyaes/blockfeeder.py python/pyaes/util.py
python/pyaes/__init__.py: external/pyaes-1.6.1/pyaes/__init__.py
    $(QINSTALL) external/pyaes-1.6.1/pyaes/__init__.py python/pyaes/__init__.py

python/pyaes/aes.py: external/pyaes-1.6.1/pyaes/aes.py
    $(QINSTALL) external/pyaes-1.6.1/pyaes/aes.py python/pyaes/aes.py

python/pyaes/blockfeeder.py: external/pyaes-1.6.1/pyaes/blockfeeder.py
    $(QINSTALL) external/pyaes-1.6.1/pyaes/blockfeeder.py python/pyaes/blockfeeder.py

python/pyaes/util.py: external/pyaes-1.6.1/pyaes/util.py
    $(QINSTALL) external/pyaes-1.6.1/pyaes/util.py python/pyaes/util.py

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

####### Install

install_libs: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/harbour-tidalplayer || mkdir -p $(INSTALL_ROOT)/usr/share/harbour-tidalplayer
	$(QINSTALL) /home/runner/work/harbour-tidalplayer/harbour-tidalplayer/external $(INSTALL_ROOT)/usr/share/harbour-tidalplayer/external

uninstall_libs: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-tidalplayer/external
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/harbour-tidalplayer/ 


install: install_libs  FORCE

uninstall: uninstall_libs  FORCE

FORCE:

