# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-tidalplayer

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Tidal player for Sailfish OS
Version:    0.2.1
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        https://github.com/sailfishos
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-tidalplayer.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   pyotherside-qml-plugin-python3-qt5
Requires:   libsailfishapp-launcher
Requires:   python3-requests

Requires:   python3-six
Requires:   python3-devel
Requires:   mpris-qt5-qml-plugin
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(python3)
BuildRequires:  desktop-file-utils

%description
A native Tidal Player for Sailfish OS written in python

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post

#mkdir %{buildroot}%{_datadir}/%{name}/python
cp -r python/tidalapi  %{buildroot}%{_datadir}/%{name}/python/tidalapi
sed -i  '114d'  %{buildroot}%{_datadir}/%{name}/python/tidalapi/user.py

cp -r python/mpegdash  %{buildroot}%{_datadir}/%{name}/python/mpegdash
cp -r python/ratelimit  %{buildroot}%{_datadir}/%{name}/python/ratelimit
cp -r python/typing_extensions %{buildroot}%{_datadir}/%{name}/python/typing_extensions

cd %{buildroot}/%{_datadir}/%{name}/python/python-future
python3 setup.py install --root=%{buildroot} --prefix=%{_datadir}/%{name}/
rm -rf %{buildroot}/%{_datadir}/%{name}/python/python-future

cd %{buildroot}/%{_datadir}/%{name}/python/isodate
python3 setup.py install --root=%{buildroot} --prefix=%{_datadir}/%{name}/
rm -rf %{buildroot}/%{_datadir}/%{name}/python/isodate

cd %{buildroot}/%{_datadir}/%{name}/python/six
python3 setup.py install --root=%{buildroot} --prefix=%{_datadir}/%{name}/
rm -rf %{buildroot}/%{_datadir}/%{name}/python/six

rm -rf %{buildroot}/%{_datadir}/%{name}/share
rm -rf %{buildroot}/%{_datadir}/%{name}/bin
cd %_builddir


# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
# >> files
# << files
