# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-tidalplayer

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Tidal player for Sailfish OS
Version:    0.1.0
Release:    20
Group:      Qt/Qt
License:    LICENSE
BuildArch:  noarch
URL:        https://github.com/sailfishos
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-tidalplayer.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   pyotherside-qml-plugin-python3-qt5
Requires:   libsailfishapp-launcher
Requires:   python3-requests
Requires:   python-dateutil
Requires:   python3-six
Requires:   python3-devel
Requires:   amber-mpris
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(python3)
BuildRequires:  desktop-file-utils
# BuildArch:      noarch

%description
A native Tidal Player for Sailfish OS written in python


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post

mkdir -p %{buildroot}%{_datadir}/%{name}/python
cp -r python/tidalapi  %{buildroot}%{_datadir}/%{name}/python/

# Copy python modules that were built by COPIES
if [ -d python/mpegdash ]; then
    cp -r python/mpegdash  %{buildroot}%{_datadir}/%{name}/python/mpegdash
fi
if [ -d python/ratelimit ]; then
    cp -r python/ratelimit  %{buildroot}%{_datadir}/%{name}/python/ratelimit
fi
if [ -f python/typing_extensions.py ]; then
    cp -r python/typing_extensions.py  %{buildroot}%{_datadir}/%{name}/python/typing_extensions.py
fi
if [ -f python/six.py ]; then
    cp -r python/six.py  %{buildroot}%{_datadir}/%{name}/python/six.py
fi
if [ -d python/dateutil ]; then
    cp -r python/dateutil  %{buildroot}%{_datadir}/%{name}/python/dateutil
fi

# Install setup.py packages using INSTALLS
# python-future, isodate, and six are handled by INSTALLS in .pro file

# Clean up any unwanted directories from INSTALLS
rm -rf %{buildroot}/%{_datadir}/%{name}/share
rm -rf %{buildroot}/%{_datadir}/%{name}/bin


# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
# >> files
# << files
